[project]
name = "codementor"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "copilotkit>=0.1.66",
    "docling>=2.56.1",
    "duckduckgo-search>=8.1.1",
    "ipykernel>=7.1.0",
    "langchain-docling>=1.1.0",
    "langchain-mcp-adapters>=0.1.11",
    "langfuse==2.60.8",
    "minio>=7.2.18",
    "openai>=2.6.1",
    "paddleocr[all]>=3.3.1",
    "pdf2image>=1.17.0",
]
